"""Deterministic discrete-event simulation substrate for CADI C2."""

from .engine import DiscreteEventSimulator
from .events import EventKind, SimEvent
from .faults import FaultClass, FaultInjector, FaultRecord, ProbabilisticFaultDecision
from .fault_linkage import (
    CrossLayerFaultInjector,
    FaultOutcomeClass,
    FaultOutcomeLinker,
    FaultOutcomeRecord,
)
from .fault_campaign import (
    FAULT_CAMPAIGN_SCHEMA,
    POLICY_FAULT_BINDING_SCHEMA,
    FaultCampaignManifest,
    FaultReplayEntry,
    FaultReplayError,
    FaultScheduleReplayer,
    PolicyFaultBinding,
    assert_paired_policy_reuse,
)
from .fault_oracle import (
    FAULT_RECORD_SCHEMA,
    FaultTrustOracle,
    FaultTrustReport,
    fault_record_from_dict,
    fault_record_from_json,
    fault_record_to_dict,
    fault_record_to_json,
    fault_records_from_jsonl,
    fault_records_to_jsonl,
)
from .resources import (
    NetworkLink,
    ReplicaRuntime,
    ReplicaRuntimeStatus,
    ResourceModel,
    ResourceTask,
    StateTransfer,
    TaskStatus,
    TransferStatus,
    Worker,
    WorkerStatus,
)
from .semantic_adapter import (
    AdapterOutcome,
    AttemptProjection,
    AuthoritativeOutcome,
    ContinuityAdapter,
    SemanticActionRecord,
    assert_authoritative_equivalent,
    authoritative_outcome,
)
from .scenarios import (
    C1_FAILURE_REFERENCES,
    FAILURE_SCENARIOS,
    REPRESENTABILITY_SCHEMA,
    SCENARIO_BY_CATALOGUE_ID,
    SCENARIO_BY_NAME,
    SCENARIOS,
    WORKLOAD_SCENARIOS,
    ScenarioDefinition,
    ScenarioEvent,
    ScenarioFamily,
    ScenarioSchedule,
    ScenarioStep,
    assert_same_seed_replay,
    build_scenario_schedule,
    replay_scenario,
    scenario_definition,
    trace_fingerprint,
)

__all__ = [
    "DiscreteEventSimulator",
    "EventKind",
    "SimEvent",
    "FaultClass",
    "FaultInjector",
    "FaultRecord",
    "ProbabilisticFaultDecision",
    "CrossLayerFaultInjector",
    "FaultOutcomeClass",
    "FaultOutcomeLinker",
    "FaultOutcomeRecord",
    "FAULT_CAMPAIGN_SCHEMA",
    "POLICY_FAULT_BINDING_SCHEMA",
    "FaultCampaignManifest",
    "FaultReplayEntry",
    "FaultReplayError",
    "FaultScheduleReplayer",
    "PolicyFaultBinding",
    "assert_paired_policy_reuse",
    "FAULT_RECORD_SCHEMA",
    "FaultTrustOracle",
    "FaultTrustReport",
    "fault_record_from_dict",
    "fault_record_from_json",
    "fault_record_to_dict",
    "fault_record_to_json",
    "fault_records_from_jsonl",
    "fault_records_to_jsonl",
    "NetworkLink",
    "ReplicaRuntime",
    "ReplicaRuntimeStatus",
    "ResourceModel",
    "ResourceTask",
    "StateTransfer",
    "TaskStatus",
    "TransferStatus",
    "Worker",
    "WorkerStatus",
    "AdapterOutcome",
    "AttemptProjection",
    "AuthoritativeOutcome",
    "ContinuityAdapter",
    "SemanticActionRecord",
    "assert_authoritative_equivalent",
    "authoritative_outcome",
    "REPRESENTABILITY_SCHEMA",
    "ScenarioFamily",
    "ScenarioStep",
    "ScenarioEvent",
    "ScenarioSchedule",
    "ScenarioDefinition",
    "SCENARIOS",
    "WORKLOAD_SCENARIOS",
    "FAILURE_SCENARIOS",
    "SCENARIO_BY_NAME",
    "SCENARIO_BY_CATALOGUE_ID",
    "C1_FAILURE_REFERENCES",
    "scenario_definition",
    "build_scenario_schedule",
    "trace_fingerprint",
    "replay_scenario",
    "assert_same_seed_replay",
]
